<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-07-11 03:22
=======
# Generated by Django 5.0.7 on 2024-07-11 21:55
>>>>>>> 8da5056bc9c0ef8474439e7ec4c9b6cc57e3e5b9

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('region_number', models.SmallIntegerField()),
=======
                ('region_number', models.PositiveSmallIntegerField()),
>>>>>>> 8da5056bc9c0ef8474439e7ec4c9b6cc57e3e5b9
                ('region_name', models.CharField(max_length=200)),
                ('capital_city', models.CharField(max_length=200)),
                ('map', models.ImageField(upload_to='map')),
                ('telephone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
    ]
